spring:
  application:
    name: nacos-customer # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址 182.254.171.122:8848
        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。


server:
  port: 28080 # 服务器端口。默认为 8080
